// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrainWatchSystem.Entities
{
    public partial class RailCarType
    {

        public RailCarType()
        {
            RollingStocks = new HashSet<RollingStock>();
        }
        
        [Key]
        public int RailCarTypeID { get; set; }
        [Required]

        [StringLength(30)]
        public string Name { get; set; }
        [Required]

        [StringLength(100)]
        public string Commodity { get; set; }
        [InverseProperty("RailCarType")]
        public virtual ICollection<RollingStock> RollingStocks { get; set; }
    }
}