// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace TrainWatchSystem.Entities
{
    public partial class RailCarType
    {
        
        [Key]
        public int RailCarTypeID { get; set; }
        public string Name { get; set; }
        public string Commodity { get; set; }

        public virtual ICollection<RollingStock> RollingStocks { get; set; }
    }
}